### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by BenfenYU** [Mukosame/AODA#1]
Hello, thank you for your excellent work ! 
When will you give the code ?

**Comment by xiaoting-hub** [comment]
Hi, your work is excellent. May I ask where I can find the Scribble datasets?
It would be great if you could reply to me. Thank you.

**Comment by Mukosame** [comment]
@xiaoting-hub The scribble dataset is available here: https://github.com/arnabgho/iSketchNFill#scribble-dataset

**Comment by Mukosame** [comment]
Hi @BenfenYU , thanks for your interest in this project!
The code will be released within the next few days.

**Comment by Mukosame** [comment]
Hi all, the codes have been uploaded. Happy holiday!
