### ISSUE TITLE
Steps to train SketchyCOCO "cat" dataset

### ISSUE THREAD

**Issue by teyou** [Mukosame/AODA#3]
Thanks for the awesome work!

After we downloaded and extracted the data into ./datasets/Object/
There are 3 different folders (i.e. Edge , GT and Sketch)

My questions:
1. What are the steps required in order to train a `cat` images  (i.e. class no 17) so that we can use it for "Photo-to-Sketch Synthesis"? It appears that it is required to create `trainA` , `trainB` folder? how could we restructure it from the original dataset?
2. What are the parameters to use for `train.py` ?

**Comment by Mukosame** [comment]
Hi @teyou , thanks for your interest in this work!

You can put the cat folder under the trainA/trainB folder, so the structure would be like: trainA/cat/xxx.png. In my network, I choose A to be the sketch and B to be the image. 

Depending on the number of classes in your folder, you may need to change --n_classes in the arguments. The other parameters, I remember I just modified the --lambda_A=10.0 and --lambda_E=1.0, the others should be the default values.

Lemme know if you have any questions in training!

**Comment by teyou** [comment]
@Mukosame thanks for your reply. I would try it out.
